version: '3.8'

services:
  smainsite-2:
    container_name: con-dmishanin-ru-2
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:80"
    expose:
      - 80
    restart: unless-stopped
    environment:
      - REACT_APP_DIRECTUS_URL=${REACT_APP_DIRECTUS_URL}
      - REACT_APP_DIRECTUS_TOKEN=${REACT_APP_DIRECTUS_TOKEN}
    volumes:
      - ./client/public/uploads:/usr/share/nginx/html/uploads
    networks:
      - npm_net

networks:
  npm_net:
    external: true
    name: npmnet

